### ISSUE TITLE
Images not displaying within Strapi Dashboard (GCP App Engine)

### ISSUE THREAD

**Issue by dompascal** [Lith/strapi-provider-upload-google-cloud-storage#104]
When using the below config for within GCP App Engine, images are not displaying within the Strapi dashboard and I am seeing 404 errors in the browser console. I have try unform and fine grained acces control on the bucket and I still seeing the issue with the bucket.

```
module.exports = {
  upload: {
    provider: "google-cloud-storage",
    providerOptions: {
      bucketName: "#bucket-name#",
      publicFiles: false,
      uniform: false,
      basePath: "",
    },
  },
};
```

What can be done so these images are not public, but accessible within Strapi? Are there extra permissions I need to change within GCP?

**To Reproduce**
1. Log into Strapi dashboard
2. Navigate to Media Lib
3. Upload a image to the storage bucket
4. 403 errors are displayed under the console tab in the browser console

**Expected behavior**
Images uploaded in the Strapi dashboard are visible withn the Strapi

**Screenshots**
<img width="1295" alt="Screenshot 2021-07-31 at 07 05 15" src="https://user-images.githubusercontent.com/211091/127730529-ca767a48-1c7a-4753-9403-2639ef2ba950.png">

**Desktop**
 - OS: MacOS
 - Browser Google Chrome
 - Version 92.0.4515.107

**Comment by dennisMKI** [comment]
It seems like this is identical to #87. 
They work on a solution for this as part of strapi v4 plugin: https://github.com/strapi/strapi/issues/8623
