### ISSUE TITLE
Plugin not considered

### ISSUE THREAD

**Issue by alessandro-candon** [Lith/strapi-provider-upload-google-cloud-storage#111]
**Describe the bug**
The plugin is not considered. I follow the doc step by step without success.

**To Reproduce**
1. download strapi version : 3.6.8
2. install plugin
3. create file `plugins.js` with this configuration 
```
module.exports = {
  upload: {
    config: {
      provider: 'strapi-provider-upload-google-cloud-storage',
      providerOptions: {
        bucketName: 'mybucketname',
        publicFiles: true,
        uniform: false,
        serviceAccount: {mysecretserviceaccount},
        basePath: '',
      },
    },
  }
}
```
4. run `npm run develop`
5. upload a file from UI
6. check on GCP storage -> no file is present -> no error is dieplayed 

**Expected behavior**
The file is uploaded.
An error is displayed.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome 

Any idea? I think the plugin is not considered form strapi...

**Comment by j2bd** [comment]
Hi @alessandro-candon 
It seems that your file plugin.js has the configuration of the plugin v4.0.0
I guess you should try this config which is slighly different : https://www.npmjs.com/package/strapi-provider-upload-google-cloud-storage/v/3.6.8

Nevertheless, unfortunately, with the same Strapi config (3.6.8) and the plugin 3.6.8 with the related plugin.js configuration, I've got the same problem as yours : the plugin is not considered and I don't any error to help me...

**Comment by alessandro-candon** [comment]
Nice, 
I started using strapi some weeks ago, so I'm not expert, do you think is better to move on version 4? Is it stable right now?

**Comment by PiecePaperCode** [comment]
exakt same issue here. tring to move away from local storage to google cloud. As i use strapi as a cloud run docker container.

**Comment by Lith** [comment]
Hi, 

The configuration for Strapi 3.6.8 is different with Strapi 4.0.0.
If you have installed by mistake the wrong version, you can try this solution below.

Edit your configuration files `plugins.js` with the correct plugins configuration for Strapi 3.6.8 :
```
module.exports = {
  upload: {
      provider: 'google-cloud-storage',
      providerOptions: {
        bucketName: 'mybucketname',
        publicFiles: true,
        uniform: false,
        serviceAccount: {mysecretserviceaccount},
        basePath: '',
    },
  }
}
```

Re-install the plugins with the version 3.6.8  : 

```
npm install strapi-provider-upload-google-cloud-storage@3.6.8
```

or with yarn : 
```
yarn add  strapi-provider-upload-google-cloud-storage@3.6.8
```

Then, relaunch a strapi build with clean : 

```
strapi build --clean
```

Then, we can relaunch your strapi instance with : 
```
strapi develop
```

Hope this will help,

**Comment by j2bd** [comment]
Hi @Lith 

I've installed the brand new version 4.0 of Strapi
I've installed your strapi-provider-upload-google-cloud-storage v4.0 (with yarn add strapi-provider-upload-google-cloud-storage) and I've configured plugin.js & middlewares.js exactly as it's clearly stated in your readme.file 

But it doesn't work and Strapi keeps on uploading file locally (after yarn build clean & yarn develop) and I'm so sad...

Any ideas that could help me ? ...

Thanks & regards

`module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: 'strapi-provider-upload-google-cloud-storage',
      providerOptions: {
        serviceAccount: {
          "type": "service_account",
          "project_id": "kitts-storage",
          "private_key_id": "fd2864b9c94a94bea697fb191eab4df593429b47",
          "private_key": "-----BEGIN PRIVATE KEY----------END PRIVATE KEY-----\n",
          "client_email": "kitts-prod@kitts-storage.iam.gserviceaccount.com",
          "client_id": "106638550522862882237",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kitts-prod%40kitts-storage.iam.gserviceaccount.com"
        },
        bucketName: 'kitts-strapi-dev-staging',
        basePath: '',
        baseUrl: 'https://storage.googleapis.com/kitts-strapi-dev-staging',
        publicFiles: true,
        uniform: false
      }
    }
  }
});`

**Comment by Lith** [comment]
Hi !

Strapi 4.0.0 has a bug with the upload provider, and image are saved in local... 

Let me see if this bug has been fixed.

Thanks !
