### ISSUE TITLE
Thumbnails/Images not shown in strapi media library

### ISSUE THREAD

**Issue by BrunoVanDamme** [Lith/strapi-provider-upload-google-cloud-storage#112]
**Describe the bug**
After successfully uploading some files to a GCS bucket, the thumbnails or images are not displayed in strapi media library.

**To Reproduce**
1. Go to 'Media Library', drag and drop a file and click on upload 1 asset to the library
2. The log files say "File successfully uploaded to https://storage.googleapis.com/**BUCKETNAME**/WP_20160421_001_edf7fab957/WP_20160421_001_edf7fab957.jpg"
3. The log files say "[2021-12-16 00:54:16.692] http: GET /upload/files?sort=updatedAt:DESC&page=1&pageSize=10 (83 ms) 200" => i receive a 200 code back
4. However, the files are not shown correctly. 

![image](https://user-images.githubusercontent.com/74254739/146284123-136f7a02-cf16-4945-91fd-1d09c5e20572.png)

5. When opening / editing the file, and copying the link and pasting in the address bar i can see the picture correctly 

![image](https://user-images.githubusercontent.com/74254739/146284242-dbcc7d5e-fba8-4472-9cc5-80f548042dce.png)
![image](https://user-images.githubusercontent.com/74254739/146284273-e3f0c0a1-402e-4159-876e-e94349c53302.png)

7. When searching in the code, it references the correct link. 

![Knipsel](https://user-images.githubusercontent.com/74254739/146284430-26aaa8fd-e803-4dae-b3d2-58211671ef53.PNG)

8. plugins.js

`module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "strapi-provider-upload-google-cloud-storage",
      providerOptions: {
        serviceAccount: {MYSERVICEACCOUNT},
        bucketName: "MYBUCKETNAME",
        publicFiles: true,
        uniform: false,
        basePath: "",
      },
    },
  },
  //...
});`

9. A folder is created every time a file is uploaded? I don't know if that's the normal behaviour. 

**Expected behavior**
The images to be shown correctly.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]

**Comment by Lith** [comment]
Hello,

You need to manage security CORS rules, like explain in README : 
- https://github.com/Lith/strapi-provider-upload-google-cloud-storage#setting-up-strapisecurity-middlewares-to-avoid-csp-blocked-url

Thanks,

**Comment by BrunoVanDamme** [comment]
Thanks Lith, works fine now!
