### ISSUE TITLE
Does it support in Heroku?

### ISSUE THREAD

**Issue by PandhuWibowo** [Lith/strapi-provider-upload-google-cloud-storage#119]
Dear @Lith 

Currently, i'm working with Strapi v4, Google Cloud Storage, and will be deployed on Heroku, my issue is Does it support in my environment?

**Comment by Lith** [comment]
Hello @PandhuWibowo,

Yes he should, but I've not test it, so do not hesitate to share your experience !

Thanks

**Comment by PandhuWibowo** [comment]
Okay, I'll try if my issue should be solved
