### ISSUE TITLE
Should not require Project Owner permission

### ISSUE THREAD

**Issue by ngdnghia28** [Lith/strapi-provider-upload-google-cloud-storage#12]
**Is your feature request related to a problem? Please describe.**
Should not require Project Owner permission.
It's too dangerous. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ningacoding** [comment]
you can use **Storage Administrator** and works!!
(still dangerous, but not as Owner role)

documentation should be updated.

**Comment by Lith** [comment]
I changed the README with your remark, indeed, Owner role is not necessary and a little bit dangerous :)
I hope this will be sufficient, do not hesitate to provide your own solution.
Thanks
