### ISSUE TITLE
Getting wrong Google Cloud Storage link to show the file

### ISSUE THREAD

**Issue by PandhuWibowo** [Lith/strapi-provider-upload-google-cloud-storage#120]
Dear @Lith,

I have following your package and the instructions, and grateful for uploading really works. But when get the file, return the image is broken. When I open the GCS Console, there are couple of files overthere. Just broken when open in Strapi Dashboard.

What happened for this situation?

I'm using Strapi v4.
And this is the error.
[Error](https://ibb.co/nCjv53x)

**Comment by Lith** [comment]
Hello @PandhuWibowo ,

I think you missed to configure security policy.
You can find all information about it here: 
- https://github.com/Lith/strapi-provider-upload-google-cloud-storage#setting-up-strapisecurity-middlewares-to-avoid-csp-blocked-url

Thanks :)

**Comment by PandhuWibowo** [comment]
Okay the source is correct right now, but still broken,

Still getting error like this
Refused to load the image 'https://accounts.google.com/ServiceLogin?service=cds&passive=1209600&continue=https://storage.cloud.google.com/cms-strapi-storage/thumbnail_21876030_029_main_9b125bd0d8/thumbnail_21876030_029_main_9b125bd0d8.jpeg?width%3D658%26height%3D866&followup=https://storage.cloud.google.com/cms-strapi-storage/thumbnail_21876030_029_main_9b125bd0d8/thumbnail_21876030_029_main_9b125bd0d8.jpeg?width%3D658%26height%3D866' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: storage.cloud.google.com".

I have implemented you instruction about security tho

**Comment by PandhuWibowo** [comment]
I think found the issue, when base url is `https://storage.googleapis.com` return the source will have similar base url. In fact, return from server should be https://storage.cloud.google.com/bucket-name/blabla/blabla.jpg

So that's why I got https://storage.googleapis.com/cms-strapi-storage/thumbnail_zara_ea338dc351/thumbnail_zara_ea338dc351.png?width=1280&height=539

```
thumbnail_zara_ea338dc351.png:1 GET https://storage.googleapis.com/cms-strapi-storage/thumbnail_zara_ea338dc351/thumbnail_zara_ea338dc351.png?width=1280&height=539 403
```

**Comment by PandhuWibowo** [comment]
Resolved.

**Comment by ambigos1** [comment]
Solved by updating security at
./config/ middlware.js(or .ts)

 {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:', 'http:'], // <-- http is for it display the image on local enviorment
          'img-src': ["'self'", 'data:', 'blob:', 'storage.googleapis.com'],
          'media-src': ["'self'", 'data:', 'blob:', 'storage.googleapis.com'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
