### ISSUE TITLE
Wierd directory name

### ISSUE THREAD

**Issue by slavmin** [Lith/strapi-provider-upload-google-cloud-storage#15]
Hi there!
Do not know if that is issue... but when uploading image from content field, directory with wierd name created. Like that for example (application::article.article).
I beleve it is becouse of code string 125 in index.js :
const backupPath = file.related && file.related.length > 0 && file.related[0].ref ? `${file.related[0].ref}` : `${file.hash}`
Consider shortening it to :
const backupPath = `${file.hash}`

**Comment by Lith** [comment]
Hello @slavmin,

Thanks for your report !
When you upload a file from Strapi Admin, in fact, the file name use related ref `application::article.article` by example.
But if you do the same from a custom website with the `ref` `article/{id}/`, the file will be upload into the directory `article/{id}/`.

The `related ref` are important, personally I used it to upload my file to GCS into the good directory.
If I remove the `related[0].ref`, my file will be uploaded into the root path... and to manage it, it's more difficult.

I hope this explanation was clear enough.
Thanks,
