### ISSUE TITLE
Load configuration from environment variables?

### ISSUE THREAD

**Issue by hrmcdonald** [Lith/strapi-provider-upload-google-cloud-storage#16]
**Is your feature request related to a problem? Please describe.**
I cannot seem to figure out how to configure settings via some sort of config files.

**Describe the solution you'd like**
I'd like to be able to set the service account, region, and bucket name via js configuration so that they can be loaded from environment variables.

**Describe alternatives you've considered**
It seems like this might already be possible, but I have no idea how to do this and it might help to update the documentation to outline how.

**Comment by hrmcdonald** [comment]
I found a similar solution here. I will fork and test this out locally to let you know how it goes: https://github.com/orhankutlu/strapi-provider-upload-aws-s3-extended

**Comment by Lith** [comment]
Hi @hrmcdonald ,

Thanks for your report.
You can provide change and make a PR.
Also, if I found time, I will add it :)

Thanks !

**Comment by Lith** [comment]
Hi @hrmcdonald, I've made an update available to test 👍  
Please give me some feedback about it.
Thanks,
