### ISSUE TITLE
Strapi beta.20

### ISSUE THREAD

**Issue by meinvolk** [Lith/strapi-provider-upload-google-cloud-storage#19]
The migration guide for 19.4 -> 20 states the following. Is this something the package supports?

> "A lot of our users have been requesting that we move some back-end specific configurations to files. While implementing the media library feature, we decided to move the upload plugin settings to files.
> 
> This means that you now have to configure your provider directly in the files. You can read the documentation here to update."

**Comment by Lith** [comment]
Hi @meinvolk,

Are you talking about latest update by setting up configuration with environment variable ?
- https://github.com/Lith/strapi-provider-upload-google-cloud-storage#optional---setting-up-strapi-from-environment-variable

Thanks :)

**Comment by meinvolk** [comment]
Yea, that seems right. Thanks you!

**Comment by Lith** [comment]
@meinvolk : I will update the README in next Strapi release with further more information 👍
