### ISSUE TITLE
Not Compatible with Node v11.1.0

### ISSUE THREAD

**Issue by rjain15** [Lith/strapi-provider-upload-google-cloud-storage#2]
`error strapi-provider-upload-aws-s3@3.0.0-beta.8: The engine "node" is incompatible with this module. Expected version "^10.0.0". Got "11.1.0"`

I am not sure if this is because of strapi not compatible with v11?

I am using strapi-docker and running into this issue.

**Comment by Lith** [comment]
Hi, 

Strapi is not working with Node 11, you need to use Node 10 only :)
Also, you use AWS, it's not the good GitHub project ^^ 

Thanks
