### ISSUE TITLE
Configuration per environment

### ISSUE THREAD

**Issue by noqcks** [Lith/strapi-provider-upload-google-cloud-storage#20]
I would like to use the standard Strapi Upload when running in dev/local, but use Google Cloud Storage for upload when running in production. Is there any way to do this?

I see that [this is possible](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#configuration-per-envrionment) for the S3 upload plugin.

Thank you for your help. I'm quite new to strapi.

**Comment by Lith** [comment]
Hello @noqcks,

I will update the documentation in the next update but for now, you can use environment variable like explain in README (optional parts).

The plugin does working like AWS 3 version, with latest update of Strapi (than remove administration part).

If you need more help about, you can talk to me on Strapi Slack.

Thanks,

**Comment by Lith** [comment]
New release with full documentation is now available !
