### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by benedictjohannes** [Lith/strapi-provider-upload-google-cloud-storage#23]
**Describe the bug**
I'm really new to Strapi, so forgive my ignorance. I tried to find "Strapi Upload Settings" (that sounds like a GUI `textfield` that can be found in the Admin interface, but I didn't find it. Per Strapi [upload documentation](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider), I found that the upload configuration is in `./extensions/upload/config/settings.json`. Copy paste the *entire* content of *Service Account JSON* downloaded from Google didn't help. Instead, I tried specifying options in it, such as
```json
{
    "provider": "google-cloud-storage",
    "providerOptions": {
      "serviceAccount": "<copy paste the whole 'Service Account JSON' object replacing this string>",
      "bucketName": "<theBucketName>",
      "bucketLocation": "us",
      "baseUrl": "<theBaseUrl>"
    }
  }
```
After which, the plugin complains with `Error parsing data "Service Account JSON", please be sure to copy/paste the full JSON file.` which apparently I did.

**Expected behavior**
Documentation should list clearly where to "copy paste" the service account JSON. Trying to follow this plugin documentation and Strapi official docs seems not resulting in anything.

**Software versions:**
OS: openSUSE Tumbleweed 20200422, Node v12.16.1, Strapi/strapi-admin 3.0.0-beta.20

**Comment by Lith** [comment]
Hello @benedictjohannes,

I've worked this weekend on the documentation, the latest release is now available with all explanations you need :)

Thanks

**Comment by benedictjohannes** [comment]
Thank you @Lith , I've seen your last commit cf6fec7 / v20.1 that you have really clarified the docs and also eliminated the serivceAccount string assertion I suggested in my PR #24. 

There's just one more thing, when I started the Strapi project, it creates production/development/staging directories under `/config/environments`, in which there are config files (`/config/environments/<development|staging|production>/custom.json`). In my previous test, I see that they are available only in `strapi.config.currentEnvironment`. Would you support merging config in separate environment files in specifying GCS connection? This provide another way of providing config (IMHO easier).

**Comment by Lith** [comment]
You need to follow instructions describe in README with the new upload configuration files.

look the third example with a different configuration by environment :)

**Comment by filipecrosk** [comment]
Hi @Lith I tried copying/pasting the JSON from Gcloud but I'm getting an error:
`Error: Error parsing data "Service Account JSON", please be sure to copy/paste the full JSON file.`

this is my file, am I missing something?
```js
{
  "provider": "google-cloud-storage",
  "providerOptions": {
    "serviceAccount": {
      "type": "service_account",
      "project_id": "cms-etus",
      "private_key_id": "20fe164aa0adb27c673aa98cb3fd787b33488fa0",
      "private_key": "-----BEGIN PRIVATE KEY-----\......",
      "client_email": "strapi-api@cms-etus.iam.gserviceaccount.com",
      "client_id": "10938178...",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/strapi-api%40cms-etus.iam.gserviceaccount.com"
    },
    "bucketName": "etus-cms",
    "baseUrl": "https://storage.googleapis.com/etus-cms"
  }
}
```

**Comment by filipecrosk** [comment]
I was able to fix it changing the file `/lib/index.js` line 25 from:

```
const serviceAccount = JSON.parse(config.serviceAccount);
```

to
```
const serviceAccount = config.serviceAccount;
```

Should I paste the content of the downloaded JSON file as a string?

**Comment by Lith** [comment]
Hello @filipecrosk ,

JSON file need to be copy/paste as string and not json directly.

I will check to add this two possibilities into the plugin, but we can’t convert to JSON only because many people use old system with configuration save in database as string.

Thanks,

**Comment by benedictjohannes** [comment]
I solved this by checking type of serviceAccount key supplied in config.
in `/lib/index.js` line 29 commit c76fec7 
```javascript
const serviceAccount = JSON.parse(config.serviceAccount);
```
You can support both old (saved as string) and new (saved as object within JSON) by

```javascript
const serviceAccount = typeof config.serviceAccount==='string' ? 
JSON.parse(config.serviceAccount) : 
config.serviceAccount
```
Which is how I did it in #24

**Comment by nikolDi** [comment]
@filipecrosk, try in third example create constant with your GSC Key, stringify it and then add to 'serviceAccount'.
Example: 

` 
 const myGcsKey = JSON.stringify({
    // JSON Service Account
  })
`

**Comment by Lith** [comment]
Thanks @benedictjohannes, yes send a new PR with this update :)  I will add it to next release !
The solution of @nikolDi is also a good tricks !

**Comment by filipecrosk** [comment]
Wow super cool to see that this community is super active. Thank you all.

**Comment by benedictjohannes** [comment]
@filipecrosk in the current version ([3.0.0-beta.20.2](https://github.com/Lith/strapi-provider-upload-google-cloud-storage/releases/tag/3.0.0-beta.20.2)) you should be able to use JSON object directly in JSON configuration in `./extensions/upload/config/settings.js`.

@Lith Since the docs has totally clear on how to configure the plugin, allow me to close this issue. 

However, I'd still suggest that the plugin read `gcs` key in Strapi custom config, which for me, looks easier compared to the the third example in docs to support different environments. I've opened another PR #25 with updated docs and plugin, please feel free to merge if you think that this benefit the plugin. 

I've also added in the docs that the GCS bucket created for the plugin in should be created with fine-grained access control (uniform access control does not work as the plugin upload files with public access control).
