### ISSUE TITLE
making doc more clear / unhandled promise

### ISSUE THREAD

**Issue by terchris** [Lith/strapi-provider-upload-google-cloud-storage#28]
I have some suggestions on how to make the documentation more clear.

Setting up Google authentication
The names must have changed since the doc was created. I believe the: 
4. From the Role list, select Storage > Administrator.
Should be:
 4. From the Role list, select Cloud Storage > Storage Administrator.

I'm not sure if this is the root cause of the problems with the configuration. But I find the other variables a bit confusing.

I think that it is a good idea to put an actual example in the documentation then explain the config variables based on that example.
There are just 3 variables involved here. But I have been struggling to figure out what they are.

serviceAccount:
It seems that I can put my google config inside the " " or not. This was not clear from the doc, but I found it in issues. If I paste it inside the " " I get the following error when starting strapi:
Server wasn't able to start properly.
error SyntaxError: .../extensions/upload/config/settings.json: Unexpected token  in JSON at position 93

bucketName:
This field I do not understand. There are 3 similar words in the config file: bucketName, Bucket-name and bucket-name. Are these the same? If so, why are they not spelled exactly the same way? What is the relationship between them? 
The explanation of bucketName points to https://cloud.google.com/storage/docs/locations?hl=fr for further explanation. 
Reading this I get a bit confused as the text on this page talks about what region the bucket is located. My bucket is in the eu region and I tried to put "bucketName": "eu"
Starting strapi I got the following error that tells me that the bucket name should not be "eu" 
:Error: Bucket names must be at least 3 characters in length, got 2: 'eu'

baseUrl:
{bucket-name} seems to me that it is a variable that is parsed by the plugin at execution time. But where is the variable set?  

My ./extensions/upload/config/settings.json looks like this:
{
    "provider": "google-cloud-storage",
    "providerOptions": {
      "serviceAccount": {
        "type": "service_account",
        "project_id": "urbalurba....",
        "private_key_id": ".....",
        "private_key": "-----BEGIN PRIVATE KEY-----...-----END PRIVATE KEY-----\n",
        "client_email": "....iam.gserviceaccount.com",
        "client_id": "...",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/urbalurba....iam.gserviceaccount.com"
      },
      "bucketName": "strapi",
      "baseUrl": "http://bucket.urbalurba.com/strapi"
    }
  }

Playing around with the variables identified a unhandled promise: 
Example #1:(node:7122) UnhandledPromiseRejectionWarning: Error: ...iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
    at new ApiError (.../node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (...i/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (.../node_modules/@google-cloud/common/build/src/util.js:134:117)
    at .../node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (.../node_modules/retry-request/index.js:206:7)
    at .../node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:7122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Example #2:
(node:11715) UnhandledPromiseRejectionWarning: Error: Cannot parse response as JSON: Not Found
    at Util.parseHttpRespBody (.../node_modules/@google-cloud/common/build/src/util.js:188:42)
    at Util.handleResp (.../node_modules/@google-cloud/common/build/src/util.js:134:117)
    at...node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (.../node_modules/retry-request/index.js:206:7)
    at .../node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Lith** [comment]
Hello @terchris,

I handle your point of view, but I think it's important to have a good base of knowledge about Google Cloud to use this plugin and Google Services.
I will try to give you more information, and made some change on the documentation (however very complete compare to others).

Don't forget to use the balise `insert code` when you copy/paste log or example, this will clarify the bug reporting for me.

`serviceAccount` can be paste as string or JSON in configuration.
If you paste it as JSON, be careful about indentation.

`bucketName` refer to a "bucket" already create on Google Cloud Storage :
- https://cloud.google.com/storage/docs/creating-buckets

You need to create a "bucket" on Google Cloud Storage before start the configuration of the plugin.

You have set the following configuration : 
```
      "bucketName": "strapi",
      "baseUrl": "http://bucket.urbalurba.com/strapi"
```
But it's not possible, except if you have configure a load balancer and create a `bucket` called `strapi` ? 
If you don't understand something (like `baseUrl`) I suggest to keep the default configuration : 

```
      "baseUrl": "https://storage.googleapis.com/{bucket-name}"
```

In the documentation the variable `{bucket-name}` refer to the bucket create on Google Cloud Storage and this one is **unique** and you not need to change it (except if you have configure a load balancing with a custom url).

Try to create a bucket, locate in "eu" with the following name : `urbalurba-eu-1`

Finally, the file should like this :
```
      "serviceAccount": "...",
      "bucketName": "urbalurba-eu-1",
      "baseUrl": "https://storage.googleapis.com/{bucket-name}"
```

Thanks,

**Comment by Lith** [comment]
@terchris , the documentation has been update following your feedback : 

1. Update of the section "Setting up Google authentication"
2. Description `serviceAccount` variable 
3. `bucketName` with the step "How to create a bucket" with the documentation and reference to "Where a bucket can be located" and review of examples and explanations provide.

Full diff can be viewed here : https://github.com/Lith/strapi-provider-upload-google-cloud-storage/commit/9f0fd51e7a1029fc5d649bc0fe7181afa94645e4

This update will be available in the next release of Strapi beta (or maybe RC !)

Hope this update will help you.
Thanks,
