### ISSUE TITLE
Cannot discern instruction in google app engine deployment documentation

### ISSUE THREAD

**Issue by FamilyMan** [Lith/strapi-provider-upload-google-cloud-storage#29]
**Describe the bug**
Cannot discern what instruction is referring to.

**To Reproduce**
1. Go to 'https://strapi.io/documentation/3.0.0-beta.x/deployment/google-app-engine.html'
2. Scroll down to 'File uploading to Google Cloud Storage'
3. Cannot discern where settings are found.

**Expected behavior**
After 'Save the JSON credentials file.', there is a line displaying 'Plugins > File Upload > Settings > Production tab'. I cannot find what this is referring to. Can there please be more detail added to this step.

**Desktop (please complete the following information):**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.3
- Database: postgres
- Operating system: windows 10

**Comment by lisongx** [comment]
I think I have the same issue, couldn't find the `'Plugins > File Upload > Settings > Production tab`

**Comment by rasimack** [comment]
If you want to upload files in Google cloud storage just follow the steps of the readme of this rep and skip this part 'Plugins > File Upload > Settings > Production tab'.

Not sure if I am missing somethings with skipping these steps you mentioned but using only the information of the this rep I could upload images successfully to my bucket.

**Comment by lisongx** [comment]
The documentation it's from this, https://strapi.io/documentation/3.0.0-beta.x/deployment/google-app-engine.html#file-uploading-to-google-cloud-storage

So I guess that need to be updated

**Comment by Lith** [comment]
Hi @lisongx , @FamilyMan , @rasimack !

The deployment documentation is deprecated and refer to older release of Strapi (<=19).
It's not manage by me, but by the Strapi Team. I will ask to update the documentation, and purpose a PR with new documentation.

Follow the plugin documentation for release 20 and next :) 

Thanks

**Comment by Lith** [comment]
For following the request :  https://github.com/strapi/strapi/pull/6275

Also, the documentation was updated but only visible for the next RC release.
