### ISSUE TITLE
Uploading shows success but file isn't really uploaded into bucket

### ISSUE THREAD

**Issue by ilkkalyyvuo** [Lith/strapi-provider-upload-google-cloud-storage#3]
Hi,

I've set service account JSON, selected multi-region name and region, ie. followed the setup instructions and everythings seems to be okay. When uploading a file to the Google storage bucket via Strapi admin UI, the upload route POST method returns a HTTP200 and an object with hash and url values etc. However, the actual file is not uploaded to the bucket and the url returned by the POST is pointing to a file which does not exist (as the file isn't really uploaded). I can upload to the bucket with gsutil or via Storage Browser UI.

Any idea what might be the issue?

Here are my project's dependencies:

"lodash": "^4.17.5",
"strapi": "^3.0.0-next.11",
"strapi-admin": "^3.0.0-beta.9",
"strapi-hook-mongoose": "3.0.0-beta.9",
"strapi-plugin-content-manager": "3.0.0-beta.9",
"strapi-plugin-content-type-builder": "3.0.0-beta.9",
"strapi-plugin-documentation": "3.0.0-beta.9",
"strapi-plugin-email": "3.0.0-beta.9",
"strapi-plugin-settings-manager": "3.0.0-beta.9",
"strapi-plugin-upload": "3.0.0-beta.9",
"strapi-plugin-users-permissions": "3.0.0-beta.9",
"strapi-provider-upload-google-cloud-storage": "^3.0.0-beta.9",
"strapi-utils": "3.0.0-beta.9"

Thanks for your help!

**Comment by Lith** [comment]
Hello @ilkkalyyvuo !
Sorry for the delay :) 

Your Strapi main version is not good in your `package.json` file.

You need to replace `"strapi": "^3.0.0-next.11" ` by `"strapi": "^3.0.0-beta.9"`.
Be careful when you update your Strapi version and never use `npm audit fixed` (because this will change your Strapi version to the bad version).

Then, re-install all package `npm install` and rebuild Strapi `strapi build` then, launch in development mode and upload will working.

Thanks !

**Comment by emildimitrov** [comment]
I have the same issue. Tried with "strapi": "^3.0.0-beta.9". and few other versions. It shows that file is saved and the logs show success, but nothing is in the bucket.

**Comment by emildimitrov** [comment]
Is anybody actually using this plugin with success? And if yes can provide details how you actually make it work

**Comment by Lith** [comment]
Hi @emildimitrov, I use this plugin for my business project without problem.
On GCP does your bucket is correctly configured in "Multi-Regional" mode ?

Have you create your bucket directly via the plugin or manually from GCP ?
Could you provide me more information about your configuration ?

Thanks :)

**Comment by emildimitrov** [comment]
Hello @Lith thanks for your quick response

My bucket is with the following config (done manually)
- Multi-region for eu
- Name is {mysite}.com, because i'm using cloudflare in front as CDN
- Bucket is public. I have allUsers having storage view role
- My service account (the key used) has storage admin & project owner roles 

Thanks :)

**Comment by Lith** [comment]
Ok, into the `upload_file` table, I've this type of url : 
```https://storage.googleapis.com/{bucketName}/{pathToFile}```
And the `provider` save is `google-cloud-storage`

If the upload succeed, all data are saved.
Does your Service Account JSON has sufficient right to write the file into the bucket ? 

I've try to re-install a new Strapi instance with GCP and a new storage bucket in EU, and everything's working for me :/

**Comment by Lith** [comment]
Also, it's important to keep Strapi up to date, could you try to update your project to the latest version ?

**Comment by emildimitrov** [comment]
I'll double check again and will let you know

**Comment by ng-hai** [comment]
Can confirm this plugin is working out of the box

```json
  "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "mysql": "^2.17.1",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.14",
    "strapi-admin": "3.0.0-beta.14",
    "strapi-hook-bookshelf": "3.0.0-beta.14",
    "strapi-hook-knex": "3.0.0-beta.14",
    "strapi-plugin-content-manager": "3.0.0-beta.14",
    "strapi-plugin-content-type-builder": "3.0.0-beta.14",
    "strapi-plugin-email": "3.0.0-beta.14",
    "strapi-plugin-settings-manager": "3.0.0-beta.14",
    "strapi-plugin-upload": "3.0.0-beta.14",
    "strapi-plugin-users-permissions": "3.0.0-beta.14",
    "strapi-provider-upload-google-cloud-storage": "^3.0.0-beta.14.1",
    "strapi-utils": "3.0.0-beta.14"
  },
```

**Comment by cpres** [comment]
works out of box for me on:
```
    "lodash": "^4.17.5",
    "strapi": "3.0.0-alpha.26.2",
    "strapi-utils": "3.0.0-alpha.26.2",
    "strapi-hook-mongoose": "3.0.0-alpha.26.2"
```

**Comment by Lith** [comment]
I close the issue, if someone has a problem please let me know ! Thanks 👍
