### ISSUE TITLE
Remove checkBucket to allow Storage Object Admin role

### ISSUE THREAD

**Issue by Tuanpm31** [Lith/strapi-provider-upload-google-cloud-storage#36]
Hi,

It's only works when services account have Storage Admin roles, but if you work in company with multiple bucket, and you allowcated a bucket with role Storage Object Admin, it's more security for another bucket in project right? 

I think we should remove checkBucket function.

Thanks

**Comment by Lith** [comment]
Hi @Tuanpm31 

`checkBucket` is a function than check if the bucket exist before uploading a file.

In the past, the plugin was creating bucket for you, but with latest Google Cloud Storage release, I've  prefered to remove this feature but keep the part "does the bucket exist yet ?".

Also, you are free to send us a PR with your request and explain your point of view :)

Thanks !

**Comment by dgmike** [comment]
And... if have a option to check the bucket with default `true`? And maybe is not necessary to check on every upload but only on `init` function. What do you think about?

**Comment by Tuanpm31** [comment]
I will create a PR for both remove check bucket and allow uniform access control, because uniform access control is recommend by google cloud storage when you create a new bucket. And it's more secure.

**Comment by dgmike** [comment]
Great!!!! :tada: show me the code.... :-D
