### ISSUE TITLE
firebase support

### ISSUE THREAD

**Issue by Maaasyn** [Lith/strapi-provider-upload-google-cloud-storage#40]
**Is your feature request related to a problem? Please describe.**
It would be nice, if I could use this provider for firebase storage, as it has a free plan, no card required and it can use same api as gcs.

**Describe the solution you'd like**
An option in configuration file, where I could specify to use an firebase storage.

**Describe alternatives you've considered**
Maybe new package, focused on the problem, as the one currently existing doesn't work.

**Comment by peterfortuin** [comment]
Firebase Storage and Google Cloud Storage is the same thing. When I deployed Strapi on Google App Engine a free Cloud Storage has been created. I use that one with this plugin. It works fine. The storage is also visible in Firebase Console.

**Comment by Prashant4900** [comment]
sir can u pls help me to identify what mistake I will do I tried every this but every time it shows the error 

![Screenshot from 2021-03-06 20-13-43](https://user-images.githubusercontent.com/62440911/110210692-dfdfcb00-7eb8-11eb-9ca1-c24af9311510.png)
![Screenshot from 2021-03-06 20-14-25](https://user-images.githubusercontent.com/62440911/110210695-e2dabb80-7eb8-11eb-981c-ad682149d1ea.png)
![Screenshot from 2021-03-06 20-16-55](https://user-images.githubusercontent.com/62440911/110210705-ebcb8d00-7eb8-11eb-80c7-95143d728049.png)
