### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by dgmike** [Lith/strapi-provider-upload-google-cloud-storage#49]
A good enhancement to the provider would be a way to inform the collaborators how to contribute with the provider. Some good topics:

- how to run unit tests
- check sign-off and how to do it
- run lint checks

A good sample: https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by Lith** [comment]
I agree with you ! I've add DCO checking yesterday.
I will wrote a CONTRIBUTING files with all information.
