### ISSUE TITLE
Use application default credentials

### ISSUE THREAD

**Issue by brettwillis** [Lith/strapi-provider-upload-google-cloud-storage#55]
When deployed on Google Cloud platforms such as App Engine, Cloud Functions, and Cloud Run, the storage SDK can use the "application default credentials". In this way you don't need to specify any service account key or credentials, the SDK automatically detects the default service account.

See https://cloud.google.com/docs/authentication/production#finding_credentials_automatically.

My suggestion: If the `serviceAccount` option is omitted, then (instead of throwing an error) construct the `Storage` instance with no options, like so:

```javascript
new Storage()
```

**Comment by Lith** [comment]
Hello @brettwillis 

Thanks for your issue, it's an interesting information :)
If you want, it will be nice to test on your side with a fork of this project ?

Unfortunately, I've no time to try this right now.

Thanks,
