### ISSUE TITLE
error: null value in column "url" violates not-null constraint

### ISSUE THREAD

**Issue by daguiheso** [Lith/strapi-provider-upload-google-cloud-storage#56]
After following the step by step suggested in https://github.com/Lith/strapi-provider-upload-google-cloud-storage, it throws error code: 500  "null value in column "url" violates not-null constraint" when trying to upload an image to strapi.

**Comment by Lith** [comment]
Hi @daguiheso,

Could you please provide more information and follow Issue bug template ?
Example available here : https://github.com/Lith/strapi-provider-upload-google-cloud-storage/issues/new?assignees=&labels=&template=bug_report.md&title=

This will help us to help you ;)

Also, provide Strapi, NPM and Node version.

Thanks,

**Comment by WiNloSt** [comment]
I encountered this error as well. Here's my setup.

Node: 12.16.1
NPM: 6.13.4
Yarn (I use yarn): 1.17.3

And here's my `dependencies` from package.json
```json
{
  "knex": "<0.20.0",
  "pg": "^8.2.1",
  "sqlite3": "latest",
  "strapi": "3.0.5",
  "strapi-admin": "3.0.5",
  "strapi-connector-bookshelf": "3.0.5",
  "strapi-plugin-content-manager": "3.0.5",
  "strapi-plugin-content-type-builder": "3.0.5",
  "strapi-plugin-email": "3.0.5",
  "strapi-plugin-upload": "3.0.5",
  "strapi-plugin-users-permissions": "3.0.5",
  "strapi-provider-upload-google-cloud-storage": "^3.0.1",
  "strapi-utils": "3.0.5"
}
```

**Comment by Lith** [comment]
Thanks @WiNloSt for this information, does this error occurs from Strapi Admin or with a custom API rest request ?

If this occurs with an API request, could you share the upload part of code ?

I will try to reproduce the problem on my side.

Thanks 🙃

**Comment by WiNloSt** [comment]
@Lith For my case, I tried uploading media from Strapi Admin. I ran the server with `yarn develop` command and I found that error from the console.

**Comment by WiNloSt** [comment]
@Lith You could try [cloning my repo](https://github.com/WiNloSt/strapi-101) to reproduce that. 🙏

Some more info about my setup.
- I bootstrap this project with `yarn create strapi-app my-project --quickstart` in less than a week ago, so all dependencies should be farily up to date.
- I use PostgreSQL as a database, I use Heroku PostgreSQL addon.
- I modified [server.js](https://github.com/WiNloSt/strapi-101/blob/master/config/server.js) by adding `url` option, I added that when testing Google Authentication.

I think those are all the changes I made so far, so it's pretty minimal. Let me know if you need anything more 👍

The reason why I want to use Google storage provider is that I'm already running Strapi on Cloud Run (GCP), so I don't want to resort to using another provider (AWS S3) which could complicate my setup a lot more.
