### ISSUE TITLE
Any guidance on large file uploads above 32mb?

### ISSUE THREAD

**Issue by devpascoe** [Lith/strapi-provider-upload-google-cloud-storage#61]
I'm having success with the provider hosting strapi on Google Cloud Run. However if i upload a file above 32mb (their hard request limit) i get the 413 large file http error.
Updated request.json etc.
```
{
  "parser": {
    "enabled": true,
    "multipart": true,
    "formidable": {
      "maxFileSize": 524288000
    }
  }
}
```

More of a hosting issue but Google App Engine i presume has similar request limits. Is the media library just not really an option for large files?
Most of what i'm trying to upload are around 50mb.

**Comment by devpascoe** [comment]
For now i have a separate Google Cloud Compute vm instance dedicated to CMS and admin with a separate Google Cloud Run config for external consumers.
A bit over the top but should scale (just wish it could be under one roof).
Perhaps on the horizon could be a file upload where it directly sends the file to google storage instead of via the POST to /upload.
❤️

**Comment by Lith** [comment]
Hello @devpascoe,

I've uploaded files over 100MB without any problem, but I use Google Cloud Storage only on dedicated hosting.
I'm not using anymore Google App Engine, so I'm not sure to help you :/

You need to check configuration limit on Strapi and on your server hosting, but GCS have a higher limitation (5 To).

Thanks

**Comment by peterfortuin** [comment]
I'm using App Engine to host Strapi (with this Google Cloud Storage plugin) and I noticed that I was able to upload bigger files if I gave the App Engine instances more memory.

**Comment by fabian-hiller** [comment]
> For now i have a separate Google Cloud Compute vm instance dedicated to CMS and admin with a separate Google Cloud Run config for external consumers.

@devpascoe did you find another better solution or did you stick with it?

**Comment by devpascoe** [comment]
> > For now i have a separate Google Cloud Compute vm instance dedicated to CMS and admin with a separate Google Cloud Run config for external consumers.
> 
> @devpascoe did you find another better solution or did you stick with it?

lol stuck with it.
