### ISSUE TITLE
Error parsing data "Service Account JSON"

### ISSUE THREAD

**Issue by geekette86** [Lith/strapi-provider-upload-google-cloud-storage#62]
I get this error with the latest version

```
error Error: Error parsing data "Service Account JSON", please be sure to copy/paste the full JSON file. at checkServiceAccount (/app/node_modules/strapi-provider-upload-google-cloud-storage/lib/provider.js:55:13) at Object.init (/app/node_modules/strapi-provider-upload-google-cloud-storage/lib/provider.js:135:26) at createProvider (/app/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:76) at module.exports (/app/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:16:36) at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:369:15) at /app/node_modules/strapi/lib/Strapi.js:376:14 at Array.map (<anonymous>) at Strapi.runBootstrapFunctions (/app/node_modules/strapi/lib/Strapi.js:375:55) at Strapi.load (/app/node_modules/strapi/lib/Strapi.js:301:16) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async Strapi.start (/app/node_modules/strapi/lib/Strapi.js:137:9)

```

**Comment by geekette86** [comment]
check my PR here #63

**Comment by Lith** [comment]
Hello @geekette86 and thanks for your issue _(a little cordiality is always a pleasure),_

This error occurs when you provide a bad configuration.
`ServiceAccount` can be a "String" or a "JSON object" but not a **file path**.

For now, file path for configuration is not available, but can be managed if it's necessary, for custom configuration, like you have done.

I've check your PR, but I can not merge it because this can produce misunderstand for others.

Thanks,

**Comment by geekette86** [comment]
Thx for the quick reply :-D , but what i did here is make life easier for soem ppl who deploy into cloud ....Thx (ps i am a devops)

**Comment by Lith** [comment]
@geekette86 : I'm little bit busy in this moment, and I'm not replying quickly  :) This is why I've provide my Strapi Slack account (you can ping me directly, for any issue).

I will review your PR in few days, and add `filePath` feature directly into the plugin.
Your update on Readme is great, but this will be better to manage `filePath` directly into.

PS : For a better comprehension, I prefer full english without "short word", I'm french and it's difficult for me to understand words like `soem ppl`.
PS 2 : I'm CTO and mom <3
