### ISSUE TITLE
Application Default Credentials from GKE throws error on Upload

### ISSUE THREAD

**Issue by martaver** [Lith/strapi-provider-upload-google-cloud-storage#67]
**Describe the bug**
I'm running strapi with the `strapi-provider-upload-google-cloud-storage` plugin on GKE. 
I've configured `bucketName` for the providerOptions, and that's it.

When I try to upload a file, I get the following error
```
[2020-09-03T12:43:35.995Z] error Error uploading file to Google Cloud Storage: Primary: /namespaces/<REDACTED_PROJECT_ID>.svc.id.goog with additional claims does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

Docs don't seem to mention GKE setups, so wondering whether this is bug.

It looks like it's trying to access the bucket through Workload Identity, but I have no idea what `/namespaces/<REDACTED_PROJECT_ID>.svc.id.goog` is referring to. What resource exactly is trying access the bucket, and what should I be granting permissions to?

An ideas?

**Comment by martaver** [comment]
If I try to manually add `/namespaces/sightful-development.svc.id.goog` to the Cloud Storage Admin role for the bucket, GCP throws me unidentified errors and creates a support ticket :-/

**Comment by Lith** [comment]
Hi @martaver ,

Sorry for the delay, I will try to help you anyway... but I hope you have find a solution since !
I've never used `GKE`, so I will make a research about it and verify if an update if necessary to work with this plugin.

If you have found a solution, feel free to share it (PR or comment).

Thanks,
