### ISSUE TITLE
Set CORS headers for uploaded assets?

### ISSUE THREAD

**Issue by scottbert** [Lith/strapi-provider-upload-google-cloud-storage#68]
**Is your feature request related to a problem? Please describe.**
My issue is that I need to set CORS headers on each item when they're uploaded. I'm using a CDN to serve assets from Strapi, this CDN is on a totally different domain name to the one the Strapi instance is running on, so trying to use "Crop" functionality for example fails.

**Describe the solution you'd like**
I'd like config to be able to specify CORS headers for the saved uploads - for my purposes it'd be a simple header shared for all uploads allowing the other domain CORS access.

**Describe alternatives you've considered**
I haven't. If there's an alternative I'd love to hear about it :) 

**Additional context**

**Comment by Lith** [comment]
Hi @scottbert,

CORS policy can be update and set in `middleware.js` file locate in `config` folder.

You have two way, define CORS for all of your environment by updating defaut `middleware.js` file under `config` :  
- `config/middleware.js`
```
module.exports = {
  settings:{
    cors: {
      origin: 'http://127.0.0.1:4200,http://127.0.0.1:1337'
    }
  }
};
```

And you can have a `middleware.js` file for each environment and define your CORS origin urls separately.

Hope this will help you,
Thanks

**Comment by scottbert** [comment]
I'm not sure if this will help, because the images when uploaded are saved to a google bucket and then accessed outside of Strapi - doesn't this middleware only apply to things being served by strapi?

**Comment by Lith** [comment]
For my case, I don't need to add GCS url to CORS policy.
Does your files are public or private ?

Have you overriding the `baseUrl` variable ?

**Comment by TimoTheus27** [comment]
Hi we have the same issue. Setting the cors in middleware.js. Doesn't help. 
We can't crop or download the assets.

```
module.exports = () => ({
  settings: {
    cors: {
      enabled: true,
      credentials: true,
      origin: ['*'],
      methods: ['*'],
    },
  },
});
```

**Comment by thiboot** [comment]
Hello ! I think i have the same issue, here are my console errors when i try to crop a file :
![Capture d’écran 2020-11-07 à 19 14 37](https://user-images.githubusercontent.com/1211351/98448699-4d0f6980-212e-11eb-8c86-f24e59d713b3.jpg)

**Comment by radkra** [comment]
Any solution for this one? I'm also struggling with it now.

**Comment by Lith** [comment]
Hello,

Sorry for the delay, I think you need to add `https://storage.googleapis.com` in allowed cors.
Edit your configuration files, and add it.

You can not used in production cors policy with `*`, it's deprecated.
You need to declare all URL authorized to used your domain and make action with it.

It's not related directly to this plugin, you can have this problem with AWS or any other storage provider too.

Thanks,

**Comment by radkra** [comment]
Hey @Lith , 
I feel the case is kinda different here. From te strapi perspective everything seems to be fine and working correctly. The problem is we save direct google storage URL of the image/media into database and then fetch it from frontend which is forbidden by cors policy - should be done with the middleware/backend. Temporary solution for me was to add corse-anywhere before google storage url on frontend.

**Comment by radkra** [comment]
Thanks for the answer! :)

**Comment by JeanLEUNG** [comment]
This CORS issue comes from the GCS bucket configuration. In order to solve it, you need to allow your origin (see your console log) in a CORS config in GCS, as described here :
https://cloud.google.com/storage/docs/configuring-cors

In my case, I created this file :
[
  {
    "origin": ["https://yoursite.com"],
    "method": ["GET"],
    "responseHeader": ["Content-Type"],
    "maxAgeSeconds": 1800
  }
]

and set up the config using gsutil :
gsutil cors set yourJsonFile.json gs://bucketName

and it worked instantly.

**Comment by radkra** [comment]
Thank you @JeanLEUNG . Going to check it soon, will let u know if it helped for me.

**Comment by doomSDey** [comment]
> 

This worked for me. On carefully studying the issue you can see that the issue is that the bucket isn't allowing the strapi to access the media because of the CORS which can be solved by adding proper CORS to the bucket. I didn't have any CORS setting to my bucket yet I faced this issue.
