### ISSUE TITLE
Images correctly uploaded but not visible later...

### ISSUE THREAD

**Issue by JomaKar** [Lith/strapi-provider-upload-google-cloud-storage#75]
help !!! Im deploying strapi to GAE. Right now the issue is that I cannot see uploaded images... so Im using the provider you've written, nevertheless, although I can upload images and review that they were correctly uploaded by going to the cloud store interface and actually see the images up there, I cannot access them. I have granted both Storage Admin and Storage Object Admin to the account service, also created keys for it, but still unable to get the images I just uploaded... getting 403 error... Does anybody has experience with this situation?

this is my plugins.js file:
`module.exports = {
    upload: {
        provider: 'google-cloud-storage',
        providerOptions: {
            bucketName: 'strapi-sqlite-post.appspot.com',
            publicFiles: false,
            uniform: false,
            basePath: ''
        },
    }
}`

![Captura de pantalla 2020-10-05 a la(s) 16 11 13](https://user-images.githubusercontent.com/17166181/95142192-c20b1000-0738-11eb-91e9-0d08110bdc96.png)
![Captura de pantalla 2020-10-05 a la(s) 16 11 47](https://user-images.githubusercontent.com/17166181/95142197-c46d6a00-0738-11eb-9b5f-8fd748c740be.png)
![Captura de pantalla 2020-10-05 a la(s) 16 24 11](https://user-images.githubusercontent.com/17166181/95142199-c5060080-0738-11eb-9daf-85ef8667912c.png)
![Captura de pantalla 2020-10-05 a la(s) 17 22 15](https://user-images.githubusercontent.com/17166181/95142200-c59e9700-0738-11eb-8249-d4dbd4d56ade.png)
![Captura de pantalla 2020-10-05 a la(s) 17 44 31](https://user-images.githubusercontent.com/17166181/95142202-c59e9700-0738-11eb-99a9-37f22ec87180.png)

**Comment by Lith** [comment]
Hello @JomaKar ,

Could you check in database if the entry has been create successfully with Strapi ?
You have a table name `upload_file`, with an `url` fields.

Could you please check it and paste some results ?

Then, try to set the variable  `publicFiles` to `true` and test if the image is visible?

Thanks,

**Comment by ettisberger** [comment]
I had the same issues minutes ago. All my uploaded files did not have public access. When I add the member allUsers in gcs all the files have public access and everything works. I think I used publicFiles: true but probably my setup with my env vars isnt 100% correct. Need to try it again to be sure tomorrow.

**Comment by Lith** [comment]
Hi @ettisberger, 

Where have you set your environment settings ?
Not sure to understand why this isn't working well, I'm not using GCP anymore, only GCS with Service Account json information.

If the file is correctly upload and the entry is create in your database, the problem concerns public access to URL.
Have you changed the `basePath` ?

Thanks

**Comment by ettisberger** [comment]
hi @Lith :)

Sorry for a late response. I had them in an .env file. In the end I did a try and set the publicFiles param to true, no basePath set and it didnt work for me. But to be honest I probably made some mistake. I didnt spend too much time for it because I only wanted to try GCP once but switched to an own cloud server now. Not sure if I have time to retest it again soon...sorry :/
