### ISSUE TITLE
Allow Option to Change Image URL

### ISSUE THREAD

**Issue by itmayziii** [Lith/strapi-provider-upload-google-cloud-storage#77]
**Is your feature request related to a problem? Please describe.**
The current options do not seem to provide a way to reference assets from a different URL than the bucket URL.

i.e. Assets may get uploaded to the bucket by referencing the bucket name but when retrieving the file from the bucket it would be nice if you could provide a different URL like a CDN you have setup that proxies the bucket. A very similar setup to GCPs documentation on adding a CDN to a bucket https://cloud.google.com/cdn/docs/setting-up-cdn-with-bucket.

I tried using the current `baseUrl` and `basePath` options but they do not seem to do what I'm suggesting. 

**Describe the solution you'd like**
The solution I would like to see would make Strapi use a defined URL instead of the storage bucket URL `https://cdn.some-site.com/{image-name}` instead of  `https://storage.googleapis.com/{bucket-name}/{image-name}` when retrieving image. The admin panel of Strapi should reference the new image URLs when previewing the image and the API should return links with the new URL instead of the GCS bucket URL.

**Comment by itmayziii** [comment]
I would be happy to look into this feature myself if you think this is something you would want to add to this project but don't have time for at the moment.

**Comment by Lith** [comment]
Hi @itmayziii ,

`baseUrl` allow you to already do that, because  I'm using it :)
Keep your bucket name, and change your `baseUrl` with the subdomain / domain you want.

Per example : 
```
baseUrl: 'https://static.domain.com' 

Then, you will be able to access to your image with :  `https://static.domain.com/image-url.jpg`

All of the configuration needs to do on Google platform. 
You need to configure CDN proxy with a load balancer.
If you follow the documentation, you will find, otherwise, let me know and I will try to help you to configure it.

Thanks,

**Comment by itmayziii** [comment]
@Lith you are 100% correct. I must have tested it wrong before. Thank you for your help.
