### ISSUE TITLE
Provision to set Cache-Control headers on images uploaded and created

### ISSUE THREAD

**Issue by saikatdas0790** [Lith/strapi-provider-upload-google-cloud-storage#79]
**Is your feature request related to a problem? Please describe.**
When benchmarking my website using Chrome Lighthouse, it gives me warnings around the cache expiration header set by default at 1 hour. I would like to be able to set this for the images uploaded and generated by the plugin. Here's a screenshot of the warnings
![image](https://user-images.githubusercontent.com/7412443/103128247-9b66d080-46ba-11eb-877b-0b56835c40b5.png)

**Describe the solution you'd like**
A setting in the plugin options that lets us set the Cache-Control headers, something like specifying it like this
"Cache-Control:public, max-age=31536000"

**Describe alternatives you've considered**
I tried setting this at the bucket level on GCS but it doesn't support. Also, I'm unsure why this plugin just doesn't make the whole bucket public and then doesn't have to deal with all the fine-grained access

**Additional context**
This will not only lead to better scores on Lighthouse but also lead to reduced GCS bills as the requester doesn't have to be served the same file again and again by GCS

**Comment by Lith** [comment]
Hi @saikatdas0790 

You need to configure this with your CDN image provider or directly on GCS.
More information about this here : https://cloud.google.com/storage/docs/metadata

Thanks,

**Comment by saikatdas0790** [comment]
@Lith But that's the thing. CORS policy for existing objects on the bucket is an imperative process. I have to run a command like this
```sh
gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" <bucket_url>
```

The issues with this is:
- This is an imperative process that needs to be done on a regular basis and it will go and run on all your objects.
- It will error out on a bunch of objects that the plugin has created as you're running this as your signed-in google cloud account and it does not have permissions on the generated files and you will have to provide permissions for them before running the above

As opposed to this process, it is more conducive to just set this during object creation. If you're using the Google Cloud NodeJS SDK, they provide options to set the metadata here
https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream

If you could help me understand the code of where to do this in the plugin, I could probably send a pull request.

**Comment by saikatdas0790** [comment]
@Lith Hi, I've figured out what needs to be done to make the above work. Is it okay if I send you a pull request?

If you check here,
https://googleapis.dev/nodejs/storage/latest/File.html#save

This is the method used here
https://github.com/Lith/strapi-provider-upload-google-cloud-storage/blob/7b41076b1ff27ce4037d2daa3eca241bf1ec3264/lib/provider.js#L179

We just need to add another field to the config options that we accept called "metadata" and that can accept corresponding parameters.

Here is the relevant documentation:
- This is [the documentation](https://cloud.google.com/storage/docs/json_api/v1/objects/insert#request_properties_JSON) for what properties the metadata can include
- This is [the docs](https://googleapis.dev/nodejs/storage/latest/global.html#CreateWriteStreamOptions) for the object being passed to the file.save() method call on line 79 here

https://github.com/Lith/strapi-provider-upload-google-cloud-storage/blob/7b41076b1ff27ce4037d2daa3eca241bf1ec3264/lib/provider.js#L179

Please respond so that I may send the pull request

**Comment by danestves** [comment]
Hi! How is going this feature? @Lith

**Comment by saikatdas0790** [comment]
I didnt receive any response from the maintainer, so didnt work on the pull request

**Comment by danestves** [comment]
@saikatdas0790 in my company we need this feature urgent, can you make a fork a upload a new npm package with this features?

**Comment by saikatdas0790** [comment]
@danestves I'm currently working on other things. But if this is a paid bounty, I could do it sooner.

Also, I suggest your team owning the package. And I could send the pull request

**Comment by Lith** [comment]
SORRY !! I've not received notification and I was working on so many other subject... I can have option of course for that !
PR are welcome and I will be glad if someone want to improve the plugin with new feature.

I will try to add this ASAP if nobody can do that now.

**Comment by KuschL** [comment]
I created a pull request to handle this via configuration. It also enables gzip support for non-binary files.
see - https://github.com/Lith/strapi-provider-upload-google-cloud-storage/pull/86

**Comment by Frank3K** [comment]
I created another PR (https://github.com/Lith/strapi-provider-upload-google-cloud-storage/pull/90) where you can complete configure the meta data, including cache-control.

**Comment by Lith** [comment]
Thank you very much @KuschL and @Frank3K. 
I've approved your PR, and I'm really sorry to be so long to respond... last months was really complicated for me 😩
