### ISSUE TITLE
Error: Error parsing data "Service Account JSON", please be sure to copy/paste the full JSON file. With using process.env vars

### ISSUE THREAD

**Issue by EgorCloud** [Lith/strapi-provider-upload-google-cloud-storage#81]
**Describe the bug**
After upgrading to Strapi 3.4.3, there was a problem with indirectly specifying variables in the config/settings.json file

**To Reproduce**
1. update to Strapi 3.4.3
2. Install `strapi-provider-upload-google-cloud-storage`
3. Write to config file:
```json
{
  "provider": "google-cloud-storage",
  "providerOptions": {
    "serviceAccount": "${process.env.GCS_SERVICE_ACCOUNT}",
    "bucketName": "${process.env.GCS_BUCKET_NAME || Bucket-name}",
    "baseUrl": "${process.env.GCS_BASE_URL}",
    "basePath": "/public",
    "publicFiles": true
  }
}

```
4. Fill .env file

**Expected behavior**
Project has been started

**Desktop (please complete the following information):**
 - OS: Windows NT 10.0; Win64; x64; rv:85.0

**Comment by obaidh** [comment]
hi mate,

try to take from .env file and past on setting.json its work for me I think the issue its format on .env file now on the plugin

**Comment by EgorCloud** [comment]
> 
> 
> hi mate,
> 
> try to copy `GCS_SERVICE_ACCOUNT` from .env file and past on setting.json its work for me I think the issue its format on .env file, not on the plugin

@obaidh, yes, your method actually works. But I'm still wondering how this can be done using a .env file.
The .env file is correct, considering that the method described in the issue worked up to version 3.4.3.
I already found a solution using the /config/plugins.js file, which I don't really like considering the kind of file architecture the Strapi team suggests to use.
So I'm still wondering if the method described in the issue will work?

**Comment by Lith** [comment]
@PepinNucleaire has submit a PR with a quickfix about this.
Hope this will help !
