### ISSUE TITLE
Protected content

### ISSUE THREAD

**Issue by baermathias** [Lith/strapi-provider-upload-google-cloud-storage#83]
Is it already possible to protect media content with your plugin in any way?
I have followed this discussion (https://github.com/strapi/strapi/issues/8623) and it seems that there is currently no way to secure media content, which means that there are many use cases, where user related content would be shared to anybody: user images, invoices, orders, audio messages, video messages, etc.

**Comment by twentyfortysix** [comment]
I'm also interested know how to ;)

**Comment by Carduelis** [comment]
As far as I understood, there are two modes:
```javascript
{
   publicFiles: true; // false
}
```

And there is no way to have a granular control: it's either public or private.
How is it possible to turn on [ACLs](https://cloud.google.com/storage/docs/access-control/lists) mode? 

> Subject to object ACLs means fine-grained, object-level access control lists (ACLs) are enabled. Objects may be public if they grant access to allUsers or allAuthenticatedUsers.  [Learn more](https://cloud.google.com/storage/docs/cloud-console#_sharingdata)

From the documentation of this plugin:

> The bucket should be created with fine grained access control, as the plugin will configure uploaded files with public read access.

Which means, some kind of preperation for custom access for documents/folders. Is it right?

**Comment by SunSparc** [comment]
I have recently started configuring this plugin for some users at my company. We are also wanting the files to remain private, however, the plugin will only try to access them via public URL as far as I can tell. Are there any plans to allow Strapi and this GCS plugin to access files in a private bucket?
