### ISSUE TITLE
Google Cloud Storage not working when publicFiles : false 

### ISSUE THREAD

**Issue by echtme** [Lith/strapi-provider-upload-google-cloud-storage#87]
Hey,

I'm running Strapi on Google Cloud Run. I can upload images and also see them in the Cloud Storage Bucket.
However, the image preview doesn't work in Strapi (img link is correct), only when I set the **publicFiles** setting to **true**. But I don't want to share these images publicly.

Also, I tried to add the JSON  key, but still the same issue. 

./config/plugins.js

`module.exports = {

upload: {

    provider: "google-cloud-storage",

    providerOptions: {

      bucketName: "mybucketnamehere",

      publicFiles: false,

      uniform: false,

      basePath: ""
    },
    },
    };

**Comment by dafstone** [comment]
I am just another user of this project, but it seems to me what you're requesting here is out of the scope of this plugins functionality.  This manages the upload to GCS and returns the URL for display -- if you set `publicFiles` to false, you are specifically blocking these files from being seen publicly, which is also how Strapi loads them into the administration panel.  If you look at the image links you'll see these are just GCS asset paths by default.  

What you want would require building some kind of authentication pattern for the admin application when an image is set that way, which is a pretty substantial change and would seem to me to be outside the parameters of what this plugin is supposed to do.

**Comment by Lith** [comment]
Related to this : https://github.com/strapi/strapi/issues/8623 
We are working on it, hope provide solution with Strapi V4 plugin ;)
