### ISSUE TITLE
Unable to upload file in Google Storagee

### ISSUE THREAD

**Issue by kdpisda** [Lith/strapi-provider-upload-google-cloud-storage#9]
`AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at new AssertionError (internal/assert.js:269:11)
`
Followed the steps present in the `readme`

**Comment by noqcks** [comment]
Did you resolve this? I'm also having the same issue

**Comment by askvarun** [comment]
I had the same issue and resolved it with the following steps:

The storage bucket created in GCP needs to have Access control : Fine-grained
as mentioned in readme.
"The bucket should be created with fine grained access control, as the plugin will configure uploaded files with public read access."
